### ISSUE TITLE
https://posthog.github.io/charts-clickhouse/ returns 404

### ISSUE THREAD

**Issue by tiina303** [PostHog/charts-clickhouse#125]
## Is your feature request related to a problem?

https://posthog.github.io/charts-clickhouse/ returns 404

## Describe the solution you'd like

We see something similar to https://posthog.github.io/charts/ ideally with a PostHog logo too. We should also redirect folks from there to the clickhouse charts.

## Describe alternatives you've considered

as is

**Comment by fuziontech** [comment]
https://github.com/PostHog/charts-clickhouse/commit/35b10da94598091ca83660f3b47ffd30ac17dc6d
https://github.com/PostHog/charts/commit/16b55852e1a3f784594d8e8efd4cf716e8ef9eda
