### ISSUE TITLE
 HTTPS certificate error

### ISSUE THREAD

**Issue by liule** [PostHog/charts-clickhouse#133]
## Bug description

*I deployed a new postog in AWS and prompted success through helm chart, but the HTTPS certificate was wrong in the end. The certificate prompt was "kubernetes progress controller fake certificate"*

*If helm install or upgrade failed include your `values.yaml` (without sensitive data) and output from `kubectl describe nodes`.*

## values.yaml

cloud: "aws"
ingress:
  hostname: posthog.*.*.*
  nginx:
    enabled: true
  letsencrypt:
    enabled: true
certManager:
  enabled: true

clickhouseOperator:
  storage: 100Gi

postgresql:
  persistence:
    size: 50Gi

kafka:
  persistence:
    size: 20Gi
  logRetentionBytes: _8_000_000_000

web:
  replicacount: 3

worker:
  replicacount: 3

plugins:
  replicacount: 3

## How to reproduce

1.
2.
3.

## Environment

- helm-chart & EKS

**Comment by tiina303** [comment]
Could you check in <your hostname>/preflight & see if `SSL/TLS certificate` has a green checkmark or not? If yes, then I'd trust that, you can also try visiting from incognito or someone else from a different location. Browsers sometimes see recent changes as suspicious, which is great for web safe usage normally, but can throw us off here.

**Comment by liule** [comment]
![posthog-issue](https://user-images.githubusercontent.com/1271719/135013516-44ef75f9-331d-48a8-8c9e-56660368da03.png)
Sorry, I didn't see the green checkmark

**Comment by tiina303** [comment]
If you click on either just experimenting or live implementation - you'll see what's up/what's not.

**Comment by liule** [comment]
SSL/TLS certificate has a green checkmark, but After entering, the certificate is still wrong

**Comment by liule** [comment]
https://posthog.m.umu.co/

**Comment by tiina303** [comment]
That link doesn't look like PostHog to me, I see the "Welcome to OpenResty!" page & no certificate errors

**Comment by liule** [comment]
13.113.132.190 posthog.m.umu.co

**Comment by liule** [comment]
Sorry, You need to add a host record. I haven't mapped DNS yet

**Comment by tiina303** [comment]
I can't access that IP either.

**Comment by liule** [comment]
![Uploading 9707F920-8761-4E81-BDD4-1CAED85ED3C3.png…]()

**Comment by fuziontech** [comment]
👋 Hey @liule. You need to setup your DNS before the cert will be issued via _lets_encrypt_
https://cert-manager.io/docs/configuration/acme/

Once you have your DNS records setup correctly `cert-manager` should grab a new cert from let's encrypt and you'll be good to go!
