### ISSUE TITLE
Ability to customize annotations for individual ingress routes

### ISSUE THREAD

**Issue by BojanOro** [PostHog/charts-clickhouse#148]
## Is your feature request related to a problem?

When using PostHog in environments with high security requirements it would be nice to have different Ingress rules for the various routes. Namely, I want to be able to expose routes that are required for ingesting traffic to a publicly accessible Ingress Controller, while exposing the Web UI routes to only an internal Ingress Controller accessible over VPN.

## Describe the solution you'd like

The ability to set annotations for the ingress configuration for each route. 

In the end state in my particular configuration I'd like to have:

1. An Ingress that would be my public space, with my default public ingress and no additional annotations, that would cover all paths other than `/`
2. An Ingress for the `/` path that would have additional annotations that I can use to either change the ingress class to point to my internal ingress controller or adding extra Nginx annotations to whitelist a particular IP address.

I am a Helm amateur so I can't comment on the best way to do this, but even letting users override the Ingress template entirely would permit this functionality.

## Describe alternatives you've considered

I have looked at existing PostHog functionality for this.

https://posthog.com/docs/self-host/configure/securing-posthog#handbook-content-menu-wrapper#restrict-access-by-ip

Organizationally we already do much of our access security by either using internal ingress controllers or whitelisting IPs on the Nginx side. It would be preferable to bring PostHog inline with that use case, and can be combined with PostHog's existing functionality to provide defence-in-depth from a networking access perspective.

## Additional context

Working in healthcare, I've found it much easier to convince enterprise security teams to permit novel applications when you can seal it off in a box protected by a VPN!

**Comment by guidoiaquinti** [comment]
Hey @BojanOro, thank you for your report.

What you describe makes sense, but it would complicate our baseline setup quite a bit. Can you please share an example of an ingress definition that might work for your use case? 

> I am a Helm amateur so I can’t comment on the best way to do this, but even letting users override the Ingress template entirely would permit this functionality.

+1. In this case, my suggestion is to:
1. use our chart and Helm to render the kubernetes definitions (example: `helm template -f values.yaml --output-dir='/tmp/your_directory' posthog/posthog`)
1. make all the customizations you need
1. apply the definitions to the cluster `kubectl apply -f /tmp/your_directory/*`

**Comment by guidoiaquinti** [comment]
@BojanOro please take a look at ☝️ and let me know if it works for you. I'm going to close this issue for now.
