### ISSUE TITLE
Investigate downtime during deployment

### ISSUE THREAD

**Issue by guidoiaquinti** [PostHog/charts-clickhouse#176]
## Bug description
A customer running on AWS is reporting some downtime during `helm` operations. They are running with 2 replicas for `web`/`events`.

 
## Expected behavior
No downtime expected

## How to reproduce
_"It appears that helm creates two new nodes, and terminates the old ones. But it terminates them before the new pods become ready / healthy. For example I can see this shortly after an upgrade, causing NGINX to show a 503 for all requests."_
```
NAME                                                READY   STATUS    RESTARTS   AGE
posthog-web-c4bc4b487-4msjb                         0/1     Running   0          54s
posthog-web-c4bc4b487-cxzhn                         0/1     Running   0          54s
```
## Environment

- [X] Deployment platform (gcp/aws/...): AWS (possibly everywhere)
- [X] Chart version/commit: latest
- [X] Posthog version: latest

## Additional context
* See [private Slack channel](https://posthogusers.slack.com/archives/C02EAFFA11S/p1635866041034200)

**Comment by Legion2** [comment]
I think the downtime is related to the way the deployments are added via Helm, all deployments are annotated as helm hooks, so helm will create and delete them as part of this lifecycle.
https://github.com/PostHog/charts-clickhouse/blob/4273cd1e9bc982cc1bc08642f0bcad759deeec13/charts/posthog/templates/web-deployment.yaml#L11-L15
I think this is a mistake, that the deployments are configured as hooks.

**Comment by guidoiaquinti** [comment]
> I think the downtime is related to the way the deployments are added via Helm, all deployments are annotated as helm hooks, so helm will create and delete them as part of this lifecycle.
> 
> https://github.com/PostHog/charts-clickhouse/blob/4273cd1e9bc982cc1bc08642f0bcad759deeec13/charts/posthog/templates/web-deployment.yaml#L11-L15
> 
> 
> I think this is a mistake, that the deployments are configured as hooks.

You are on point! [Here's](https://github.com/PostHog/charts-clickhouse/pull/179) an attempt to remove them but it's currently blocked by some issues in `posthog/posthog`
