### ISSUE TITLE
Evaluate the deprecation of the `beat` deployment

### ISSUE THREAD

**Issue by guidoiaquinti** [PostHog/charts-clickhouse#177]
## Is your feature request related to a problem?
We currently run two specific deployments for `beat` and `workers`. We could probably simplify this setup by deprecating the `beat` deployment and reconfigure `workers` to run `./bin/docker-worker-celery --with-scheduler` instead of `./bin/docker-worker-celery`. 

I'm not aware of any downside doing that (as it's also how we run PostHog Cloud) but we should probably double check everything works as expected before moving forward.

## Describe the solution you'd like
Less resources to maintain.

## Describe alternatives you've considered
Do nothing.

## Additional context
See conversation in our [internal Slack](https://posthog.slack.com/archives/C02GY4TFSEA/p1635931447001000)

**Comment by mariusandra** [comment]
Beat was separated in the chart since that's how it was in the original template I adapted. We then integrated redbeat to not have an extra beat dyno on heroku, costing money. It has worked without a hitch so far, and I guess the separate beat pod can be killed

**Comment by guidoiaquinti** [comment]
Thank you for the additional context @mariusandra ! 🙇
