### ISSUE TITLE
Document backup / retention methods

### ISSUE THREAD

**Issue by joesaunderson** [PostHog/charts-clickhouse#178]
## Is your feature request related to a problem?

We have just launched the Clickhouse stack and are now testing it in anger. 

Previously, we were on the Postgres stack which had the DB in RDS (which has auto snapshot and retention settings). 

We'd love to have the same level of backups / retention on the Clickhouse stack.

## Describe the solution you'd like

We'd like to know how & what to backup on the Clickhouse stack (Clickhouse events? Postgres data?)

## Describe alternatives you've considered

Not run any backups.

#### *Thank you* for your feature request – we love each and every one!

**Comment by guidoiaquinti** [comment]
Hi @joesaunderson ! With https://github.com/PostHog/posthog.com/pull/2370 we’ve just published a new _ClickHouse_ section in our runbooks that I hope will answer your questions about this service. 

Regarding PostgreSQL: we should make it explicit in our docs but we suggest you to back up the data as well like you were doing before moving analytics queries to ClickHouse.  

Let me know if this is 👍 and if we can consider this issue ✅ 

Have a good day!

**Comment by joesaunderson** [comment]
Hey @guidoiaquinti - thanks for this, it really helps my understanding on how things work. I guess a couple of questions:

- How simple is it to install the automated backup, it looks fairly simple, but would we need to build this into Helm? Could it be added automatically?

- This covers Clickhouse really nicely, do we need to backup the Postgres DB if it's within the K8s stack?

**Comment by guidoiaquinti** [comment]
> How simple is it to install the automated backup, it looks fairly simple, but would we need to build this into Helm? Could it be added automatically?

We are not planning to add ClickHouse backup/restore to Helm for now, but we can re-evaluate this in the future. 

> This covers Clickhouse really nicely, do we need to backup the Postgres DB if it’s within the K8s stack?

Yes, our suggestion is to back up PostgreSQL as well daily/bi-daily (depending on your requirements). If you don’t have a specific reason to run stateful services in K8S we also suggest that you run them “outside” Kubernetes.

Example: if you are running on AWS, you could use AWS Aurora for PostgreSQL and AWS MSK for Kafka (unfortunately there isn’t yet a _ClickHouse as a service solution_.

Let me know if this makes sense!

**Comment by joesaunderson** [comment]
> We are not planning to add ClickHouse backup/restore to Helm for now, but we can re-evaluate this in the future.

I'm not so familiar with Helm, but does this mean if we add it, and you guys push an update for the chart, we'd need to add it again? 

> If you don’t have a specific reason to run stateful services in K8S we also suggest that you run them “outside” Kubernetes.

> `Example: if you are running on AWS, you could use AWS Aurora for PostgreSQL and AWS MSK for Kafka`

Makes sense, we are looking into this, would it make sense to mention this on the AWS docs, along with some 'recommendations' on the size of the Postgres / Kafka instances?

**Comment by guidoiaquinti** [comment]
> I’m not so familiar with Helm, but does this mean if we add it, and you guys push an update for the chart, we’d need to add it again?

It depends on how you mange your k8s cluster. You can either:

1. manage the PostHog via our Helm charts + run an additional `kubectl` command to install the `clickhouse-backup` related resources.
1. extend our Helm chart and add whatever additional bits you need

> Makes sense, we are looking into this, would it make sense to mention this on the AWS docs, along with some ‘recommendations’ on the size of the Postgres / Kafka instances?

Yes, we can add that. For PostgreSQL / Kafka instance size it’s difficult to know upfront without having more data about your expected volume of events, unique people, retention policy, etc... My suggestion is to start with the same values you currently use in Helm and then add capacity if necessary.

**Comment by guidoiaquinti** [comment]
@joesaunderson I've also added https://github.com/PostHog/posthog.com/pull/2372 to our docs in order to make it more clear (and apologise as it wasn't before). Let me know if you have all the answers you need and I'll mark this issue as ✅

**Comment by joesaunderson** [comment]
@guidoiaquinti I think this can be ✅

**Comment by joesaunderson** [comment]
@guidoiaquinti I have also added https://github.com/PostHog/posthog.com/pull/2389
