### ISSUE TITLE
e2e chart testing

### ISSUE THREAD

**Issue by tiina303** [PostHog/charts-clickhouse#183]
## Is your feature request related to a problem?

Unit testing is great and we're already working on it. Adding full e2e tests would give us even more confidence and to be able to move fast without breaking things.

## Describe the solution you'd like

We create e2e tests for all our platforms (DO, AWS, Azure, GCP).
We'll have a cluster we continuously use only for these tests, we'll run max 1 concurrently per cluster. This means these won't be ran on each PR most likely but rather on master in PostHog repo, which helps also catch when PostHog app version breaks data ingestion completely. We'll use this for automated release branch testing too.

The test will:
1. send some data & check it's there
2. try to upgrade the existing deployment and check that the data is still there
3. nuke the cluster & try a new install

## Describe alternatives you've considered

continue to manually test things

## Additional context

We already have https://github.com/PostHog/vpc/blob/main/client_values/posthog/values.yaml & https://github.com/PostHog/posthog/actions/workflows/vpc-deploy.yml

**Comment by macobo** [comment]
This doesn't invalidate this ticket, but there's already a test deployment running on every PR: https://github.com/PostHog/charts-clickhouse/blob/main/.github/workflows/test-helm-chart.yaml

The suite is currently failing for unknown reasons. 

Before getting into setting up tests in more advanced configurations, it is worthwhile to get this in order as well.

**Comment by tiina303** [comment]
Among others we should set-up e2e tests against https://github.com/PostHog/charts-clickhouse/blob/main/do_1_click_values.yaml (Do 1-click values file)

**Comment by guidoiaquinti** [comment]
> This doesn't invalidate this ticket, but there's already a test deployment running on every PR: https://github.com/PostHog/charts-clickhouse/blob/main/.github/workflows/test-helm-chart.yaml
> 
> The suite is currently failing for unknown reasons.
> 
> Before getting into setting up tests in more advanced configurations, it is worthwhile to get this in order as well and use the same test suite for checking whether ingestion works as in there.

I did a first pass with https://github.com/PostHog/charts-clickhouse/pull/189. More will follow.

**Comment by yakkomajuri** [comment]
Done given we deprioritized Azure
