### ISSUE TITLE
Failled vanilla install

### ISSUE THREAD

**Issue by jalberto** [PostHog/charts-clickhouse#185]
## Bug description

Vanilla installation fails with no custom `values.yaml` with

`Error: failed to install CRD crds/clickhouse_installation_template.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"`

## Expected behavior

Install the chart

## How to reproduce

1. Add repo, update repo
2. helm install --create-namespace --namespace posthog posthog posthog/posthog
3. Error: failed to install CRD crds/clickhouse_installation_template.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"

## Environment

- [ ] managed kubernetes in scaleway
- [ ] latest in repo
- [ ] default for chart

**Comment by tiina303** [comment]
Are you on k8s 1.22?

**Comment by jalberto** [comment]
Yes

**Comment by tiina303** [comment]
Sorry about that, here's the issue we have for it https://github.com/PostHog/charts-clickhouse/issues/164 I will look into it this week

**Comment by jalberto** [comment]
thanks!

**Comment by tiina303** [comment]
Please follow the linked issue for updates, we'll be prioritizing that in the near future
