### ISSUE TITLE
Clickhouse nodeSelector can not be set to a custom value when using the clickhouse operator

### ISSUE THREAD

**Issue by Legion2** [PostHog/charts-clickhouse#210]
## Bug description
Clickhouse nodeSelector can not be set to a custom value if using the clickhouse operator.
The helm chart only allows to set a boolean value for `clickhouseOperator.useNodeSelector`

## Expected behavior

The `nodeSelector` property can be set to a custom list of node selectors

## Actual behavior

Only `clickhouse: true` can be set as node selector.

## How to reproduce

1. try to install the posthog chart with custom node selector for the clickhouse instance

## Environment

- [ ] Deployment platform (AWS/Azure/DigitalOcean/GCP/...): not relevant
- [ ] k8s version (server version from `kubectl version`): not relevant
- [ ] Chart version/commit (`helm list -n posthog`):  `5.1.0`
- [ ] Posthog version: `1.30.0`

**Comment by tiina303** [comment]
@guidoiaquinti

**Comment by guidoiaquinti** [comment]
👋 Hey @Legion2, thank you for your report.

Would be ok if we add a `clickhouse.nodeSelector` variable where you can pass a map? I can't easily change the current `clickhouseOperator.useNodeSelector` without making a breaking change. 

I anyway agree that we should deprecate the current `clickhouseOperator.useNodeSelector` as it is not very useful.

**Comment by Legion2** [comment]
@tiina303 yes I think calling the option `clickhouse.nodeSelector` is the best, becaues it is consistent with the other node selector options of the other components.

**Comment by guidoiaquinti** [comment]
@Legion2 for some reason I can't add you as reviewer but do you mind to 👀 ☝️? It should fix your issue. Thank you and have a good weekend!
