### ISSUE TITLE
Allow to use existing cert-manager and ClusterIssuer

### ISSUE THREAD

**Issue by Legion2** [PostHog/charts-clickhouse#211]
### Proposed change

If a cluster already contains a configured instance of cert-manager, it should be possible to use it with the posthog chart.
To allow this, it must be independencly configurable that cert-manager is used, but without including it's chart, because it may already exist in the cluster. Also it must be possible to configure the name of the `ClusterIssuer` and skip its creation to use an existing one.

### Alternative options

Disable the cert-manager in the posthog chart config and manually create the tls cert with the existing cert manager and configure the generated tls cert as "existing tls secrets" in the posthog chart.

**Comment by tiina303** [comment]
@guidoiaquinti who recently worked on cert manager related stuff

**Comment by guidoiaquinti** [comment]
👋 Hi @Legion2, thank you for your report. It's not documented but I think you can already archive that by:

1. setting `cert-manager.enabled:false`: to don't install any `cert-manager` resource
1. setting `ingress.letsencrypt:false`: to don't install the `ClusterIssuer` named `letsencrypt-prod`
1. add your custom annotation in the ingress definition by leveraging the `ingress.annotations` map

Let me know if this works for you!

**Comment by Legion2** [comment]
I deployed it with our own Ingress (contour HTTPProxy object) because the existing Ingress object configuration does not work with contour.

**Comment by guidoiaquinti** [comment]
👀 Contour looks like a nice project!

Are you 👍 if we close this issue? I'm asking because for what I can see, if you use our default ingress controller you can use an existing `cert-manager` and `ClusterIssuer` definition.
