### ISSUE TITLE
Allow option for PVC’s to be encrypted (AWS)

### ISSUE THREAD

**Issue by joesaunderson** [PostHog/charts-clickhouse#214]
### Proposed change

We use AWS as our cloud provider and our SRE is reporting the PVC's created by the PostHog helm chart are not conforming to our AWS Control Tower policies, this is because they are not encrypted.

Further to this, when turning on the 'Default volumes to encrypted' setting in AWS, the whole helm chart fails to install altogether.

It would be good to be able to specify the PVC as encrypted. 

### Alternative options

Don't encrypt the drives and have a non conforming stack based on our Control tower policies.

**Comment by guidoiaquinti** [comment]
Closed via #224
