### ISSUE TITLE
Allow to specify a custom storage class for clickhouse instance

### ISSUE THREAD

**Issue by Legion2** [PostHog/charts-clickhouse#215]
Currently the clickhouse instance can either be configured with an external PVC or a volumeClaimTemplate. However, the storage class of the volumeClaimTemplate can not be customized. 

https://github.com/PostHog/charts-clickhouse/blob/9000e659a96f42869315552e668cf947701fbb60/charts/posthog/templates/clickhouse_instance.yaml#L146-L150

### Proposed change
The `storageClassName` should be an optional parameter of the helm chart, if not set by the user the value is choosen based on the cloud provider. Please, also consider to use the `global.storageClass` value as default which is supported by all bitnami helm charts to globaly specify the default storage class for all persistent volumes if not specified otherwise.

### Alternative options
Workaround for setting a custom storageClass is to use the external PVC option, however then replication cannot be used.

**Comment by Legion2** [comment]
If a custom storage class is used the generation of the storage classes should be disabled.

Usecase: We want to use aws gp3 storage with the new EBS CSI driver and therefore created a custom storage class.

**Comment by guidoiaquinti** [comment]
Closed via #224
