### ISSUE TITLE
Redis password reference is wrong since update to redis 14.6.2 chart

### ISSUE THREAD

**Issue by Legion2** [PostHog/charts-clickhouse#218]
## Bug description
This chart assumes that the redis password is configured with `redis.password`, however since `14.0.0` of redis chart the password is configured at `redis.auth.password`.

## Expected behavior
If I set `redis.auth.password` in the configuration, this value should be recogniced by the chart and used as password.

## Actual behavior
posthog web and event pods do not use the password.

## How to reproduce

1. deploy the chart with `redis.auth.password` set to some value
2. see that the deployment of beat fails

## Environment

- [ ] Deployment platform (AWS/Azure/DigitalOcean/GCP/...): aws
- [ ] k8s version (server version from `kubectl version`): 1.20
- [ ] Chart version/commit (`helm list -n posthog`): 6.0.0

**Comment by guidoiaquinti** [comment]
Here's the PR that introduced the regression https://github.com/PostHog/charts-clickhouse/pull/31/. I'll try to take a look next week.

**Comment by guidoiaquinti** [comment]
Sorry for the delay here @Legion2 🙏  but between COVID, end of year holidays and a couple of issues re-prioritized I didn't have much time to work on this. 

https://github.com/PostHog/charts-clickhouse/pull/248 should fix this issue. I'm planning to merge it as soon as it gets reviewed.

**Comment by guidoiaquinti** [comment]
Closing as #248 is now merged. @Legion2 feel free to re-open or ping me if something doesn't work as expected. Thank you!
