### ISSUE TITLE
posthog upgraded  faile

### ISSUE THREAD

**Issue by liule** [PostHog/charts-clickhouse#235]
ignore

**Comment by liule** [comment]
We want to upgrade to 1.31 Version 1, directly modified values Yaml added the image version. It was found that the upgrade failed and the postog migrate error log
![image](https://user-images.githubusercontent.com/1271719/147626618-d6fce4ed-a5eb-45ad-8a55-1962a893da7b.png)
![image](https://user-images.githubusercontent.com/1271719/147626634-330b6804-b9ae-4975-a25e-49c60dce2b46.png)

**Comment by tiina303** [comment]
What chart version are you using (did you run `helm repo update`?)?

**Comment by guidoiaquinti** [comment]
@liule I'm closing this issue as I see you've edited your first comment with an `ignore`. Feel free to re-open if you want to report anything else.

Thank you and happy new year!
