### ISSUE TITLE
Document using node selectors for clickhouse

### ISSUE THREAD

**Issue by macobo** [PostHog/charts-clickhouse#307]
### Proposed change

Clickhouse nodes often need to be larger than other nodes. Let's document this + how to use `clickhouse.nodeSelector` for assigning the pods to the correct nodes.

## Additional context

cc @guidoiaquinti you've been responsible for the shape of the docs - which existing doc would you add this to or where (in the docs hierarchy) would this make sense?

**Comment by guidoiaquinti** [comment]
Hey Karl, let me know if https://github.com/PostHog/posthog.com/pull/3035 fixes the issue.

**Comment by guidoiaquinti** [comment]
@macobo I'm closing as fixed. Feel free to reopen if I've missed anything. Have a good weekend!

**Comment by macobo** [comment]
Thanks, great work!
