### ISSUE TITLE
Raise an error if externalService is used without service.enabled being false

### ISSUE THREAD

**Issue by macobo** [PostHog/charts-clickhouse#318]
### Proposed change

If `service.enabled` is true, `externalService` values are ignored. This can cause errors due to typos.

We should raise errors for example `externalClickhouse.host` is set but `clickhouse.host` is not.

### Alternative options

Let users debug

## Additional context
Ran into this doing https://github.com/PostHog/charts-clickhouse/issues/279 - typos are inevitable!

We can use a similar system to our current backwards incompatibility errors.

**Comment by a3n7** [comment]
Hey @macobo, let me know if #319 solves this
