### ISSUE TITLE
Ability to set ALLOWED_IP_BLOCKS environment variables

### ISSUE THREAD

**Issue by khumps** [PostHog/charts-clickhouse#322]
### Proposed change
Add a config option to the helm chart to set ALLOWED_IP_BLOCKS as documented in https://posthog.com/docs/self-host/configure/securing-posthog

### Alternative options
There currently doesn't appear to be any way to set this

**Comment by guidoiaquinti** [comment]
> ALLOWED_IP_BLOCKS

👋 Hey @khumps, did you try with `env`, `web.env` or other env inputs available in `values.yaml`?

**Comment by khumps** [comment]
> > ALLOWED_IP_BLOCKS
> 
> 👋 Hey @khumps, did you try with `env`, `web.env` or other env inputs available in `values.yaml`?

I totally missed that in `values.yaml`. Currently running into issues with this due to us using terraform + helm but that issue is outside of the scope of this. Thanks!

**Comment by guidoiaquinti** [comment]
> 

No problem at all, happy you've resolved your issue!
