### ISSUE TITLE
AWS documentation

### ISSUE THREAD

**Issue by macobo** [PostHog/charts-clickhouse#36]
## Is your feature request related to a problem?

Let's add documentation on how to deploy to AWS.

## Describe the solution you'd like

Skip cloudformation madness.

Instead:
1. Link to some guide on how to set up EKS
2. Give a guide for setting up on AWS (e.g. values, etc).

## Describe alternatives you've considered

Cloudformation madness. We've seen this doesn't really work as the helm action and chart quickstart is quite raw.

**Comment by tiina303** [comment]
I've updated the readme, but still need to look into why certificate didn't work properly

**Comment by tiina303** [comment]
Related: https://github.com/PostHog/charts-clickhouse/issues/57
