### ISSUE TITLE
Cannot deploy posthog using k8s and helm chart

### ISSUE THREAD

**Issue by tienpvse1** [PostHog/charts-clickhouse#369]
## Bug description
I've followed the instruction in the document, and it leads to error
Even when I tried to config values in values.yml file it cannot be deploy either

## Expected behavior
Posthog should start normally

## Actual behavior
Sometime, the "posthog-web" pod say "clickhouse_driver.errors.NetworkError: Code: 210. Try again (clickhouse-posthog:9000)"

and sometime: "cannot find table posthog.infi_clickhouse_orm_migrations_distributed"
## How to reproduce

1. follow the instruction in the official document
2. check the terminal

## Environment

- [ ] Posthog version: latest
- deploy environment: local-machine(Ubuntu 20.04)

**Comment by hazzadous** [comment]
@tienpvse1 can you provide the version of:

1. the helm chart
2. the PostHog image
3. kubectl get pods --namespace posthog
4. Details of your ClickHouse setup
5. the output of `SELECT fqdn(), name FROM clusterAllReplicas(posthog, system, tables)`

Thanks 🙏

**Comment by guidoiaquinti** [comment]
Hey @tienpvse1, I'm going to close this issue as stale. Feel free to re-open it if you are still experiencing issue or contact us in our [Slack community workspace](https://posthog.com/slack)
