### ISSUE TITLE
backup posthog

### ISSUE THREAD

**Issue by navi86** [PostHog/charts-clickhouse#382]
### Proposed change
I would like to backup posthog installation, however base on current documentation :
https://posthog.com/docs/self-host/runbook/clickhouse/backup
this is required to update "ClickHouseInstallation"
https://github.com/AlexAkulov/clickhouse-backup/blob/master/Examples.md#how-to-use-clickhouse-backup-in-kubernetes
therefore it requires to have custom version of helm chart because this version doesn't support any customisation for backup

**Comment by guidoiaquinti** [comment]
Fixed via #383 ✅
