### ISSUE TITLE
Dynamic DigitalOcean versioning

### ISSUE THREAD

**Issue by macobo** [PostHog/charts-clickhouse#44]
## Is your feature request related to a problem?

After https://github.com/digitalocean/marketplace-kubernetes/pull/233 we're really close to being in do marketplace. However the version of the chart is hardcoded there. Let's automate upgrading

## Describe the solution you'd like

Use the latest version of chart when deploying/upgrading in the scripts

## Describe alternatives you've considered

Automate creating PRs against linked repo - but this will suck resources from the maintainers.

## Additional context

cc @tiina303 you wanted to own this?

**Comment by tiina303** [comment]
Looks like there are some others who don't use the version either, e.g. https://github.com/fuziontech/marketplace-kubernetes/commit/7c7d46840d658bf2bffd0b6f0a472dfb8528dca0 
So this should be easy and fast.
