### ISSUE TITLE
switch internal Clickhouse to external Clickhouse DB::Exception: Syntax error: failed at position 64 ('-'): 

### ISSUE THREAD

**Issue by xgengsjc2021** [PostHog/charts-clickhouse#455]
Hi I tried to switch the internal Clickhouse to my external Clickhouse for my Posthog, but failed. The migration pod, 
posthog-migrate-2022-06-28-20-15-30--1-rbg2h shows the error below

```
Applying migration 0028_dead_letter_queue_settings...
    Executing raw SQL operations
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/posthog/code/ee/management/commands/migrate_clickhouse.py", line 42, in handle
    self.migrate(CLICKHOUSE_HTTP_URL, options)
  File "/home/posthog/code/ee/management/commands/migrate_clickhouse.py", line 80, in migrate
database.migrate(MIGRATIONS_PACKAGE_NAME, options["upto"], replicated=CLICKHOUSE_REPLICATION)
  File "/usr/local/lib/python3.8/site-packages/infi/clickhouse_orm/database.py", line 352, in migrate
    operation.apply(self)
  File "/usr/local/lib/python3.8/site-packages/infi/clickhouse_orm/migrations.py", line 271, in apply
    database.raw(item)
  File "/usr/local/lib/python3.8/site-packages/infi/clickhouse_orm/database.py", line 295, in raw
    return self._send(query, settings=settings, stream=stream).text
  File "/usr/local/lib/python3.8/site-packages/infi/clickhouse_orm/database.py", line 389, in _send
    raise ServerError(r.text)



infi.clickhouse_orm.database.ServerError: Code: 62. DB::Exception: Syntax error: failed at position 64 ('-'): -cluster. Expected one of: NO DELAY, end of query, INTO OUTFILE, SETTINGS, FORMAT, SYNC. (SYNTAX_ERROR) (version 21.11.10.1 (official build))
 (0)
```
During this migration, my posthog was in version: "21.0.1".

## Expected behavior
Expect to switch to the external clickhouse successfully

## Actual behavior
migration failed. 

## How to reproduce
1: posthog with internal clickhouse
2: build a new clickhouse cluster with Clickhouse-operator (https://github.com/Altinity/clickhouse-operator)
3: disable the clickhouse setting and enable the external clickhouse
4: apply the change to update the posthog
## Environment
I installed posthog with charts-clickhouse  and clickhouse-operator in EKS of AWS

## Additional context
The internal clickhouse version: 21.6.5.37
The external clickhouse version: 21.11.10
The external clickhouse can be accessed by posthog without problem. (username and password are good.)

**Comment by xgengsjc2021** [comment]
More update:
from the table below, you can see I did several combination tests, and only 1 succeed. All these 3 posthog can be installed successfully with their internal clickhouse. Only version 18.3.1 is ok to migrate the external clickhouse. I checked the logs from the migration pod, it shows various reasons. I will put here, please help check. Thanks,
<google-sheets-html-origin><style type="text/css"></style>

posthog | clickhouse | migration from internal CH to external CH
-- | -- | --
18.3.1 | 21.6.5 | Succeed
21.0.1 | 21.6.5 | failed
23.5.1 | 22.3.7 | failed

**Comment by xgengsjc2021** [comment]
Some errors shown from the migration pods:

```

infi.clickhouse_orm.database.ServerError: Code: 60. DB::Exception: Table posthog.infi_clickhouse_orm_migrations doesn't exist. (UNKNOWN_TABLE) (version 22.3.7.28 (official build))

```

```
posthog.errors.CHQueryErrorUnknownTable: Code: 60.
DB::Exception: There was an error on [chi-ch-install-ch-cluster-shard1-0:9000]: Code: 60. DB::Exception: Table posthog.sharded_session_recording_events doesn't exist. (UNKNOWN_TABLE) (version 22.3.7.28 (official build)). Stack trace:
```
```
infi.clickhouse_orm.database.ServerError: Code: 60. DB::Exception: There was an error on [chi-ch-install-ch-cluster-shard1-0:9000]: Code: 60. DB::Exception: Table posthog.person doesn't exist. (UNKNOWN_TABLE) (version 22.3.7.28 (official build)). (UNKNOWN_TABLE) (version 22.3.7.28 (official build))
```

```
DB::Exception: There was an error on [chi-ch-install-ch-cluster-shard1-0:9000]: Code: 60, e.displayText() = DB::Exception: Table posthog.sharded_session_recording_events doesn't exist (version 21.6.5.37 (official build)). Stack trace:
```

```
infi.clickhouse_orm.database.ServerError: There was an error on [chi-ch-install-ch-cluster-shard1-0:9000]: Code: 253, e.displayText() = DB::Exception: Replica /clickhouse/prod/tables/noshard/posthog/infi_clickhouse_orm_migrations/replicas/chi-ch-install-ch-cluster-shard1-0-shard1 already exists. (version 21.6.5.37 (official build)) (version 21.6.5.37 (official build)) (253)

```

**Comment by hazzadous** [comment]
I'm going to guess that you hit this issue: https://github.com/PostHog/posthog/issues/10233
i.e. you probably have a hyphen in the ClickHouse "cluster" name.

If that's the case then you could update to a release after this was merged: https://github.com/PostHog/posthog/pull/10235

With you versions experiment, I'd guess 18.3.1 didn't have the migration that fails, but 21.0.1 does. That is assuming you are using the default posthog/posthog docker image version associated with the helm chart.

If that's not the issue then 🤔

**Comment by xgengsjc2021** [comment]
@hazzadous Thanks for the update. After I removed "-", the issue is gone.

**Comment by kapil371** [comment]
how to fix 
`infi.clickhouse_orm.database.ServerError: Code: 60. DB::Exception: Table posthog.infi_clickhouse_orm_migrations doesn't exist. (UNKNOWN_TABLE) (version 22.3.7.28 (official build))`
