### ISSUE TITLE
"panic: runtime error: integer divide by zero" error after configuring clickhouse backup with remote storage azblob

### ISSUE THREAD

**Issue by gregleongf** [PostHog/charts-clickhouse#503]
When REMOTE_STORAGE variable is set to "azblob" the container throws "panic: runtime error: integer divide by zero" error.

This is related to this issue: https://github.com/AlexAkulov/clickhouse-backup/pull/450

The solution is to simply use newer version of clickhouse-backup. I've updated mine to 1.5.0

**Comment by guidoiaquinti** [comment]
Thank you for the report @gregleongf ! I've bumped the default image to 1.5.0 with ☝️ . I will merge it as soon as CI is ✅ so that you can remove the override on your end.
