### ISSUE TITLE
Different Posthog instances sharing same external resources?

### ISSUE THREAD

**Issue by connorwang** [PostHog/charts-clickhouse#546]
### Proposed change
Currently we have two Posthog instances - one prod and one dev. We just migrated dev to external resources (Kafaka, Zookeeper, Clickhouse, etc.), and we're looking to do the same with the prod instance. My understanding is that for Clickhouse and Postgresql we can specify database names, but for rest like Kafka, Zookeeper and Redis, would their be confilicts or they just work out of box?

Thanks for the awesome work!

**Comment by guidoiaquinti** [comment]
Unfortunately, we currently do not support multiple PostHog installations using the same underlying services.

**Comment by connorwang** [comment]
Thanks for the heads up. Closing the issues.
