### ISSUE TITLE
aws EKS  fail

### ISSUE THREAD

**Issue by liule** [PostHog/charts-clickhouse#59]
![image](https://user-images.githubusercontent.com/1271719/126352453-2db0e14c-79cc-40d1-b5cb-2f00c35e88b1.png)
I deployed eks in AWS for several times and reported an error after waiting for a long time. What might be the reason?

**Comment by tiina303** [comment]
Hi @liule I'd love to help and figure out what happened here, could you give me a bit more information:

1. Details about your cluster (which kind of Ec2 instances and how many do you have). E.g. output from `kubectl describe nodes` (note that by default the `eksctl create cluster` command created 2 m5.large instances for me and installing Posthog on top of that worked fine).
2. What does your `values.yaml` contain?
1. Could you run the `helm install` command you had with `--debug` flag and share the output?


I suspect that we failed to allocate something on your Kubernetes cluster, which made the `helm install` fail.

**Comment by liule** [comment]
We have replaced two eks cluster, m5.large*2 nodes. The deployment is successful. What should I do if I want to expand the Clickhouse? Now it's a 16g disk

**Comment by liule** [comment]
Will SSL certificate be automatically updated when it expires?

**Comment by tiina303** [comment]
> What should I do if I want to expand the Clickhouse?

For increasing just change the value and run `helm upgrade`

> Will SSL certificate be automatically updated when it expires?

yes, Let’s Encrypt fully automates both issuing and renewing of certificates.
