### ISSUE TITLE
Failed updates leave migrations job around ocasionally

### ISSUE THREAD

**Issue by tiina303** [PostHog/charts-clickhouse#65]
## Bug description

Failed updates leave migrations job there, so we need to run 
```
kubectl delete job -n posthog posthog-migrate
```
to clear the state

## Expected behavior

clean state after upgrade rolls back

## How to reproduce

1. run an upgrade where migration fails (e.g. --timeout too short)
2. see that migrations job sticks around

**Comment by macobo** [comment]
Note that it "sticks around" since it keeps on retrying with a backoff indefinitely :)
