### ISSUE TITLE
 Service does not have load balancer ingress IP address: posthog/posthog-ingress-nginx-controller

### ISSUE THREAD

**Issue by hanbinloop** [PostHog/charts-clickhouse#678]
## Bug description

1. My cloud server uses minikube v1.29.0, installed at helm, and here is the output when my minkube start
![image](https://user-images.githubusercontent.com/16644654/217513432-7fb5e6c0-8505-4c4e-b885-00863dc104a7.png)

2. I downloaded the chart package and repackaged it as posthoug-30.3.4.tgz using the chart packaging command. And through the `helm upgrade --install -f values.yaml --timeout 30m --create-namespace --namespace posthog posthog posthog-30.3.4.tgz --wait --wait-for-jobs --debug` to install

3. This is my values.yaml
![image](https://user-images.githubusercontent.com/16644654/217514981-54ac2fce-4460-46fb-9482-94f9cd47e0f2.png)

4. An error is displayed
![image](https://user-images.githubusercontent.com/16644654/217514481-6b6de671-a23c-4f30-8df7-e144cfa00a10.png)

The server we use is not necessarily google or Amazon, and will probably require a custom deployment. So you can't follow google's or Amazon's deployment. Need to use https://posthog.com/docs/self-host/deploy/other

**Comment by guidoiaquinti** [comment]
The problem is that you are using minikube that is an unsupported setup. The deployment is waiting for the load balancer IP, you might want to look at the [minikube docs](https://minikube.sigs.k8s.io/docs/handbook/accessing/#loadbalancer-access).

**Comment by hanbinloop** [comment]
> The problem is that you are using minikube that is an unsupported setup. The deployment is waiting for the load balancer IP, you might want to look at the [minikube docs](https://minikube.sigs.k8s.io/docs/handbook/accessing/#loadbalancer-access).

I used minikube tunnel and it was successful, but then it kept waiting for posthoug-events. I don't know why it didn't report an error
![image](https://user-images.githubusercontent.com/16644654/217530484-d56976bd-416d-4f2e-bd7b-039e1cdb7456.png)
I tried running the following `kubectl get pod -A` to check the pod situation
![image](https://user-images.githubusercontent.com/16644654/217530870-718731af-ecd1-49eb-becf-1b9376d4a568.png)

How can I keep it going

**Comment by guidoiaquinti** [comment]
Check why the pods are still waiting on the init container. I think you might have a problem with ClickHouse as I don't see its pod coming up (do you have enough k8s nodes?)
